### ISSUE TITLE
Add 2.9" WeAct E-INK

### ISSUE THREAD

**Issue by t4ndu** [btclock/btclock_v3#3]
I would like to use this board with a larger DIsplay. To do this, I take cables and connect the board to a larger display. Unfortunately I could not compile it for 2.9". Can this be adapted?
Maybe you can even extend the board to use the 2.9" display for a larger version.

**Comment by dsbaars** [comment]
Done! Implemented in d58c38c8c4fe5efee5d736d4b8003204a9bebb6d and also available through the web-flasher :)

**Comment by t4ndu** [comment]
I will test it tomorow. Thank you so mutch.

**Comment by t4ndu** [comment]
![20240322_211004](https://github.com/btclock/btclock_v3/assets/37901827/c13c6a6d-4de8-4b2e-8c79-27e1ed4b24b2)
Thank you! It works well :)
