### ISSUE TITLE
Time of the clock only UTC?

### ISSUE THREAD

**Issue by t4ndu** [btclock/btclock_v3#4]
Is the displayed time only UTC? 
is it possible to add different timezones?

(Last weekend we changed to summertime in switzerland - then i see it - over wintertime MET is equal UTC)

**Comment by dsbaars** [comment]
In the web interface you can configure the timezone offset in minutes (positive and negative), so this is already supported :)

**Comment by t4ndu** [comment]
How stupid of me... I've looked at it a hundred times and not seen it. Thank you Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Djuri Baars ***@***.***> Datum: 16.04.24  15:19  (GMT+01:00) An: btclock/btclock_v3 ***@***.***> Cc: t4ndu ***@***.***>, Author ***@***.***> Betreff: Re: [btclock/btclock_v3] Time of the clock only UTC? (Issue #4) 
In the web interface you can configure the timezone offset in minutes (positive and negative), so this is already supported :)
